version: '3'

services:

  invoicerepo:
    depends_on:
      - database
      - kafka
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: 'jdbc:postgresql://database:5432/postgres'
    build:
      dockerfile: 'Dockerfile'
      context: './'
      args:
        JAR_FILE: 'invoice-api/build/libs/invoice-api.jar'

  kafka:
    depends_on:
      - zookeeper
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOST_NAME: 'kafka:9092'

  zookeeper:
    image: 'zookeeper:latest'

  database:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "SA"
      POSTGRES_PASSWORD: "SA"